FROM almalinux
ADD https://raw.githubusercontent.com/chaitanya-online/json-path/master/src/main/java/com/example/jsonpath/service/JsonDataService.java /tmp/
ADD JAVA COLLECTIONS.zip /tmp/

# tmp is the directory name